CREATE TABLE USUARIO (
	ID INT not null AUTO_INCREMENT,
	NOME VARCHAR(50) not null,
	CPF VARCHAR(14) not null,
	USERNAME VARCHAR(50) not null,
	PASSWORD VARCHAR(100) not null,
	PRIMARY KEY(ID)) ENGINE=InnoDB; 
	

CREATE TABLE ORDEM (
	ID INT not null AUTO_INCREMENT,
	PRECO DECIMAL(6,2) not null,
	TIPO VARCHAR(20) not null,
	DATA DATETIME not null,
	STATUS VARCHAR(30) not null,
	USER_ID INT not null,
	PRIMARY KEY (ID),
	FOREIGN KEY (USER_ID) REFERENCES USUARIO (ID)) ENGINE=InnoD